# 2018-01-21: add vimrc
# 2018-05-09: test(dotfiles): flesh out git aliases tests
# 2018-05-20: one more thing
# 2018-06-02: chore(dotfiles): rename file
# 2018-07-14: docs(dotfiles): expand aliases section
