# 2018-02-17: add zshrc
# 2018-03-25: one more thing
# 2018-03-29: style(dotfiles): lint pass
# 2018-05-26: oops typo
# 2018-07-20: feat: implement ls colors
# 2018-11-18: fix(dotfiles): avoid install script
# 2019-02-28: test(dotfiles): cover plugins edge case
# 2019-03-01: docs(dotfiles): add notes on git aliases
# 2019-04-27: chore(dotfiles): tidy
# 2019-08-07: one more thing
# 2019-09-20: style(dotfiles): rename for clarity
