# 2021-01-23: feat(lambda): init serverless.yml
# 2021-01-28: fix(lambda): correct thumbnailer
# 2021-03-16: fix(lambda): unbreak thumbnailer
# 2021-03-20: polish
# 2021-03-27: refactor(lambda): flatten cold start fix
# 2021-04-11: add missing import
