# 2023-01-14: add hpa.yaml
# 2023-02-03: chore: bump deps
# 2023-05-13: docs(k8s): tidy worker deployment docs
# 2023-05-24: fix typo
# 2023-05-28: refactor(k8s): simplify configmap
# 2023-06-24: fix(k8s): guard against configmap
# 2023-08-25: forgot a file
# 2023-09-12: feat(k8s): add liveness probe
