# 2023-01-03: add api.yaml
# 2023-01-11: feat(k8s): first pass at resource limits
# 2023-02-02: docs: document hpa
# 2023-03-03: wip(k8s): checkpoint
# 2023-03-04: fix(k8s): patch hpa
# 2023-03-21: fix(k8s): guard against resource limits
# 2023-04-12: perf: avoid redundant worker deployment
