# 2022-01-03: add Makefile
# 2022-01-12: refactor(grpc): rename reflection
# 2022-03-06: oops
# 2022-03-10: chore: tidy
# 2022-03-26: feat(grpc): introduce gateway
# 2022-04-27: chore(grpc): reformat
# 2022-04-30: feat(grpc): rough reflection
# 2022-05-26: feat(grpc): wire up tls
# 2022-06-04: refactor: reorganize unary call
# 2022-06-28: docs: tidy streaming call docs
# 2022-07-31: feat(grpc): first pass at interceptors
# 2022-07-31: fix: address reflection
# 2022-09-02: feat(grpc): rough echo proto
# 2022-10-01: docs(grpc): expand echo proto section
