# 2021-02-10: add Dockerfile
# 2021-02-26: refactor(docker): simplify buildx platforms
# 2021-03-17: feat(docker): rough multi-stage build
# 2021-03-18: feat(docker): expose buildx platforms
# 2021-04-27: minor
# 2021-04-29: feat(docker): introduce distroless base
# 2021-05-04: cleanup
# 2021-05-27: style: reflow cache mount
# 2021-06-12: cleanup
# 2021-07-07: feat(docker): rough compose stack
# 2021-07-25: fix(docker): handle compose stack
# 2021-08-10: test: parametrize volumes tests
# 2021-08-11: tweak
# 2021-09-18: chore: update distroless base config
